name: ZPotato
version: '1.0'
main: fr.zeygal.zpotato.Main
api-version: '1.21'
authors: [ZEYGAL]

commands:
  hp:
    description: Main command for the Hot Potato plugin
    usage: /<command> [sub-command] [arguments]
    aliases: [hotpotato]

permissions:
  hotpotato.admin:
    description: Grants access to all admin commands
    default: op
    children:
      hotpotato.user: true

  hotpotato.user:
    description: Grants access to basic player commands
    default: true

  hotpotato.admin.create:
    description: Allows creating an arena
    default: op

  hotpotato.admin.delete:
    description: Allows deleting an arena
    default: op

  hotpotato.admin.addspawn:
    description: Allows adding a spawn point to an arena
    default: op

  hotpotato.admin.setlobby:
    description: Allows setting the lobby of an arena
    default: op

  hotpotato.admin.setspectate:
    description: Allows setting the spectator area of an arena
    default: op

  hotpotato.admin.settings:
    description: Allows configuring arena settings
    default: op

  hotpotato.admin.start:
    description: Allows starting a game
    default: op

  hotpotato.admin.stop:
    description: Allows stopping a game
    default: op

  hotpotato.admin.setmainlobby:
    description: Allows setting the main lobby
    default: op

  hotpotato.admin.unsetmainlobby:
    description: Allows removing the main lobby
    default: op

  hotpotato.admin.list:
    description: Allows listing all arenas
    default: op

  hotpotato.admin.reload:
    description: Allows reloading the plugin
    default: op

  hotpotato.user.join:
    description: Allows joining an arena
    default: true

  hotpotato.user.leave:
    description: Allows leaving an arena
    default: true

  hotpotato.user.stats:
    description: Allows checking player statistics
    default: true
