name: ZPotato
version: '1.0-BETA'
main: fr.zeygal.zpotato.Main
api-version: '1.21'
authors: [ZEYGAL]
softdepend: [PlaceholderAPI]

commands:
  hp:
    description: Main command for the Hot Potato plugin
    usage: /<command> [sub-command] [arguments]
    aliases: [hotpotato]

permissions:
  hotpotato.admin:
    description: Grants access to all admin commands
    default: op
    children:
      hotpotato.user: true
      hotpotato.admin.*: true
      hotpotato.scoreboard.admin: true

  hotpotato.admin.*:
    description: All admin sub-permissions
    children:
      hotpotato.admin.create: true
      hotpotato.admin.delete: true
      hotpotato.admin.addspawn: true
      hotpotato.admin.setlobby: true
      hotpotato.admin.setspectate: true
      hotpotato.admin.settings: true
      hotpotato.admin.start: true
      hotpotato.admin.stop: true
      hotpotato.admin.setmainlobby: true
      hotpotato.admin.unsetmainlobby: true
      hotpotato.admin.list: true
      hotpotato.admin.reload: true
      hotpotato.admin.gui: true

  hotpotato.user:
    description: Grants access to basic player commands
    default: true
    children:
      hotpotato.user.join: true
      hotpotato.user.leave: true
      hotpotato.user.stats: true
      hotpotato.scoreboard.user: true

  hotpotato.scoreboard.user:
    description: Allows seeing scoreboards during gameplay
    default: true

  hotpotato.scoreboard.admin:
    description: Allows admin access to scoreboard settings
    default: op